root_path: day-night-simple
checkpoints_dir: checkpoints
name: cycle_tri_gan_shared_segmentation_decoder_fixed
model: cycle_tri_gan_shared_segmentation_decoder
trainable: True
continue_train: False
verbose: False
print_freq: 10
display_freq: 10
save_epoch_freq: 1
load_iter: 1000
gpu_ids:
  - 0

load_size: 256
epoch_count: 50
batch_size: 1


lr_policy: linear
lr: 0.0002
beta_1: 0.5
gen_max_gnorm: 3700.
dsc_max_gnorm: 400.

dsc_model: BasePatchDiscriminator
dsc_layers: 3
dsc_channels: 64
dsc_scales:
  - 20
  - 16
  - 24
  - 32
dsc_dropout: 0.1
dsc_activ: gelu
dsc_norm: instance
dsc_padding: reflection


num_downsamples: 2
dil_channels: 64

latent_blocks: 1
latent_layers: 2

latent_channels: 64
latent_dropout: 0.1
latent_activ: gelu
latent_norm: instance
latent_padding: reflection

enc_model: DilationIntoResidualsEncoder
enc_channels: 64
enc_dropout: 0.1
enc_activ: gelu
enc_norm: instance
enc_padding: reflection
enc_dilations:
  - 1
  - 2
  - 3


dec_model: ResidualsIntoDilationDecoder
dec_channels: 64
dec_dropout: 0.1
dec_activ: gelu
dec_norm: instance
dec_padding: reflection
dec_dilations:
  - 1
  - 2
  - 3

lambda_A: 50
lambda_B: 50
lambda_idn: 20
lambda_aux: 7
lambda_aux_A: 30
lambda_aux_B: 10
adversarial_objective: mse
reconstruction_objective: L2
target_real_label: 0.9
target_fake_label: 0.1
pool_max_size: 30
pool_add_prob: 0.7

init_type: normal
init_gain: 0.02
bias: 0.0

